# Change these first
owner: zurgnflx # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: genflix.co.id
    url: https://genflix.co.id
  - name: sushiroll.co.id
    url: https://sushiroll.co.id
  - name: genflix-prd-catalog
    url: https://d3l63rih9mbuez.cloudfront.net/catalog/v1.1/pages?locale=en
    headers:
      - "Cloudfront-JWT-AppId: a597d124-03e7-43e6-8435-13d667c13c15"
  - name: genflix-prd-screen
    url: https://d3l63rih9mbuez.cloudfront.net/screen/v1.0/countries/current
  - name: genflix-prd-user
    url: https://d3l63rih9mbuez.cloudfront.net/user/v1.1/profile/38e70787-c39c-4ee1-8908-c6de48ea8cdb/public
  - name: genflix-prd-heartbeat
    url: https://d3l63rih9mbuez.cloudfront.net/heartbeat/v1.0/uptimes
  - name: genflix-prd-loyalty
    url: https://d3l63rih9mbuez.cloudfront.net/loyalty/v1.0/uptimes
  - name: genflix-prd-subscription
    url: https://d3l63rih9mbuez.cloudfront.net/subscription/v1.0/uptimes
  - name: genflix-prd-recommendation
    url: https://d3l63rih9mbuez.cloudfront.net/recommendation/v1.0/uptimes

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Genflix Uptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is genflix status page which uses **real-time** data. No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
